In [1]:
import numpy as np

# Replace this with any array of numbers you want to analyze
arr = np.array([4, 8, 15, 16, 23, 42, 56, 78, 91, 101])

# Calculate the mean
mean = np.mean(arr)
print("Mean:", mean)

# Calculate the standard deviation
std_dev = np.std(arr)
print("Standard Deviation:", std_dev)


Mean: 43.4
Standard Deviation: 34.235069738500606


In [2]:
# Generate a random 5x5 matrix
matrix = np.random.rand(5, 5)
print("Random 5x5 Matrix:")
print(matrix)

# Find the minimum values along each row
min_values_row = np.min(matrix, axis=1)
print("\nMinimum values along each row:")
print(min_values_row)

# Find the maximum values along each row
max_values_row = np.max(matrix, axis=1)
print("\nMaximum values along each row:")
print(max_values_row)

# Find the minimum values along each column
min_values_col = np.min(matrix, axis=0)
print("\nMinimum values along each column:")
print(min_values_col)

# Find the maximum values along each column
max_values_col = np.max(matrix, axis=0)
print("\nMaximum values along each column:")
print(max_values_col)


Random 5x5 Matrix:
[[0.70758952 0.78883578 0.58823087 0.18061183 0.39676253]
 [0.37140384 0.56219113 0.44105202 0.76784898 0.81324992]
 [0.95222465 0.87626232 0.50797591 0.48742768 0.24997329]
 [0.29656458 0.98072066 0.36612472 0.42247978 0.96451507]
 [0.13994126 0.64213942 0.30127869 0.79850978 0.18771844]]

Minimum values along each row:
[0.18061183 0.37140384 0.24997329 0.29656458 0.13994126]

Maximum values along each row:
[0.78883578 0.81324992 0.95222465 0.98072066 0.79850978]

Minimum values along each column:
[0.13994126 0.56219113 0.30127869 0.18061183 0.18771844]

Maximum values along each column:
[0.95222465 0.98072066 0.58823087 0.79850978 0.96451507]


In [3]:
def cosine_similarity(vec1, vec2):
    dot_product = np.dot(vec1, vec2)
    norm_vec1 = np.linalg.norm(vec1)
    norm_vec2 = np.linalg.norm(vec2)
    similarity = dot_product / (norm_vec1 * norm_vec2)
    return similarity
vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5, 6])
similarity = cosine_similarity(vec1, vec2)
print("Cosine Similarity:", similarity)


Cosine Similarity: 0.9746318461970762
